[App]
Port = 8080

[SL]
BusStop = "<location>"
SLDeparturesV4Key = "<key>"
SLServiceAlertsV2Key = "<key>"
SLStopLookupV1Key = "<key>"
SLStopsAndLinesV2Key = "<key>"

[Weather]
Lat = <int>
Lon = <int>

[Weather.Colors]
TempMin = -30
TempMid = 0
TempMax = 30

TempColorCoolCoolest = "#0033cc"
TempColorCoolHottest = "#ccd9ff"
TempColorMid = "#dee2e6"
TempColorHotCoolest = "#ffcccc"
TempColorHotHottest = "#990000"

ClassPrecip = "primary"
ClassNoPrecip = "light"
