[App]
Port = 8080

[Departures]
BusStop = "<location>"
SLDeparturesV4Key = "<key>"
SLServiceAlertsV2Key = "<key>"
SLStopLookupV1Key = "<key>"
SLStopsAndLinesV2Key = "<key>"

[Weather]
Lat = <int>
Lon = <int>

[Weather.Colors]
TempQ1 = <int>
TempQ2 = <int>
TempQ3 = <int>
TempQ4 = <int>

ClassQ1 = "info"
ClassQ2 = "primary"
ClassQ3 = "warning"
ClassQ4 = "danger"

ClassPrecip = "primary"
ClassNoPrecip = "light"
